-- 시스템 계정에서 발생

CREATE USER WEB IDENTIFIED BY WEB;
GRANT RESOURCE, CONNECT TO WEB;

---------------------------------------------
--MEMBER 관련 테이블 
--------------------------------------------

CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_GUID RAW(16) UNIQUE,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    USER_NAME VARCHAR2(15) NOT NULL, 
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(100),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
); 

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_GUID IS '회원 GUID';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원 ID';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원 PWD';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '회원 ROLE';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.PHONE IS '회원전화';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '회원 주소';
COMMENT ON COLUMN MEMBER.HOBBY IS '회원 취미';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_UNO;

SELECT SYS_GUID() FROM DUAL;

INSERT INTO MEMBER 
VALUES(
    SEQ_UNO.NEXTVAL, SYS_GUID(), 'admin', '1234', 'ROLE_ADMIN', '관리자', 
    '010-1234-5678', 'admin@iei.or.kr', '서울시 강남구 역삼동', NULL, SYSDATE, SYSDATE, DEFAULT
);

INSERT INTO MEMBER 
VALUES(
    SEQ_UNO.NEXTVAL, SYS_GUID(), 'user1', 'pass1', 'ROLE_USER', '홍길동', 
    '010-1111-5678', 'user@iei.or.kr', '서울시 강서구', NULL, SYSDATE, SYSDATE, DEFAUlt
);

INSERT INTO MEMBER 
VALUES(
    SEQ_UNO.NEXTVAL, SYS_GUID(), 'user2', 'pass2', 'ROLE_USER', '김길동', 
    '010-1111-5678', 'user@iei.or.kr', '서울시 강서구', NULL, SYSDATE, SYSDATE, DEFAUlt
);

COMMIT;

SELECT * 
FROM MEMBER;

DELETE FROM MEMBER
WHERE USER_NAME = '김희득';

DELETE FROM MEMBER
WHERE USER_NAME = '신이안';

COMMIT;

SELECT * 
FROM MEMBER;

UPDATE MEMBER
SET HOBBY = '등산'
WHERE USER_NAME = '관리자';

UPDATE MEMBER
SET STATUS = 'Y'
WHERE USER_NAME = '관리자';

SELECT USER_NO,
        USER_ID,
        USER_PWD,
        USER_ROLE,
        STATUS,
        ENROLL_DATE,
        MODIFY_DATE
FROM MEMBER
WHERE USER_ID = 'admin';

---------------------------------------------------------------------------------

CREATE TABLE BOARD (	
    "BOARD_NO" NUMBER,
    "BOARD_WRITER_NO" NUMBER, 
	"BOARD_TITLE" VARCHAR2(50), 
	"BOARD_CONTENT" VARCHAR2(2000), 
	"BOARD_ORIGINAL_FILENAME" VARCHAR2(100), 
	"BOARD_RENAMED_FILENAME" VARCHAR2(100), 
	"BOARD_READCOUNT" NUMBER DEFAULT 0, 
    "STATUS" VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    "BOARD_CREATE_DATE" DATE DEFAULT SYSDATE, 
    "BOARD_MODIFY_DATE" DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(BOARD_WRITER_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호';
COMMENT ON COLUMN "BOARD"."BOARD_WRITER_NO" IS '게시글작성자';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글내용';
COMMENT ON COLUMN "BOARD"."BOARD_ORIGINAL_FILENAME" IS '첨부파일원래이름';
COMMENT ON COLUMN "BOARD"."BOARD_RENAMED_FILENAME" IS '첨부파일변경이름';
COMMENT ON COLUMN "BOARD"."BOARD_READCOUNT" IS '조회수';
COMMENT ON COLUMN "BOARD"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "BOARD"."BOARD_CREATE_DATE" IS '게시글올린날짜';
COMMENT ON COLUMN "BOARD"."BOARD_MODIFY_DATE" IS '게시글수정날짜';


CREATE SEQUENCE SEQ_BOARD_NO;

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 43, '게시글 1',  '이 게시글은 영국에서 시작해서...', '원본파일명.txt', '변경된파일명.txt', DEFAULT, 'Y', SYSDATE, SYSDATE);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 43, '게시글 2', '이 게시글은 영국에서 시작해서..2.', '원본파일명1.txt', '변경된파일명1.txt', DEFAULT, 'Y', SYSDATE, SYSDATE);

alter table BOARD RENAME COLUMN BOARD_DATEMODIFY_DATE TO BOARD_MODIFY_DATE;

COMMIT;

SELECT * 
FROM BOARD;

UPDATE BOARD
SET BOARD_NO = 1
WHERE BOARD_TITLE = '게시글 1' ;

UPDATE BOARD
SET BOARD_NO = 2
WHERE BOARD_TITLE = '게시글 2' ;

COMMIT;

---------------------------------------------------------------------------

SELECT * FROM MEMBER WHERE USER_ID = 'admin' AND USER_PWD = '1234' AND STATUS = 'Y';
SELECT * FROM MEMBER WHERE USER_ID = 'admin' AND USER_PWD = '1234' AND STATUS = 'Y';
-- 역순으로 리스트 조회하기
SELECT B.BOARD_NO, B.BOARD_TITLE, M.USER_ID, B.BOARD_CREATE_DATE, B.BOARD_ORIGINAL_FILENAME, B.BOARD_READCOUNT
FROM BOARD B
JOIN MEMBER M ON(B.BOARD_WRITER_NO = M.USER_NO)
WHERE B.STATUS = 'Y'
ORDER BY BOARD_NO DESC;

-- 상세 조회
/*
SELECT  B.BOARD_NO, B.BOARD_TITLE, M.USER_ID, B.BOARD_READCOUNT, B.BOARD_ORIGINAL_FILENAME, B.BOARD_CONTENT, B.BOARD_CREATE_DATE, BOARD_DATEMODIFY_DATE
FROM BOARD B
JOIN MEMBER M ON(B.BOARD_WRITER_NO = M.USER_NO)
WHERE B.STATUS = 'Y' AND B.BOARD_NO=?;
*/
-- 총 게시글 갯수
-- SELECT COUNT(*) FROM BOARD

-- 조회수 증가
-- UPDATE BOARD SET BOARD_READCOUNT=BOARD_READCOUNT+1 WHERE BOARD_NO=?

-- 게시글 작성
-- INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,?,?,?,?,?,DEFAULT,DEFAULT,DEFAULT,DEFAULT)

-- 게시글 수정
-- UPDATE BOARD SET BOARD_TITLE=?,BOARD_CONTENT=? WHERE BOARD_NO=?

-- 게시글 삭제
-- UPDATE BOARD SET STATUS=? WHERE BOARD_NO=?

-- 
/* 
SELECT * 
FROM (
    SELECT ROWNUM AS RNUM, BOARD_NO, BOARD_TITLE, USER_ID, BOARD_CREATE_DATE, BOARD_ORIGINAL_FILENAME, BOARD_READCOUNT, STATUS 
    FROM (
        SELECT  B.BOARD_NO, B.BOARD_TITLE, M.USER_ID, B.BOARD_CREATE_DATE, B.BOARD_ORIGINAL_FILENAME, B.BOARD_READCOUNT, B.STATUS
        FROM BOARD B JOIN MEMBER M ON(B.BOARD_WRITER_NO = M.USER_NO) WHERE B.STATUS = 'Y'  ORDER BY B.BOARD_NO DESC
    )
)
WHERE RNUM BETWEEN 2 and 3;
*/

-----------------------------------------------------------
BEGIN
    FOR N IN 1..52
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 44, '게시글 ' || SEQ_BOARD_NO.CURRVAL , '이 게시글은 영국에서 시작해서..' ||  SEQ_BOARD_NO.CURRVAL, null, null, DEFAULT, 'Y', SYSDATE, SYSDATE);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

SELECT * FROM BOARD;

--------------------------------------------------------------------
------------------------- REPLY 관련 테이블 -------------------------
--------------------------------------------------------------------

CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER,
  REPLY_WRITER_NO NUMBER,
  REPLY_CONTENT VARCHAR2(400),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  REPLY_CREATE_DATE DATE,
  REPLY_MODIFY_DATE DATE,  
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
  FOREIGN KEY (REPLY_WRITER_NO) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_REPLY_NO;

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '댓글이작성된게시글';
COMMENT ON COLUMN "REPLY"."REPLY_WRITER_NO" IS '댓글작성자';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "REPLY"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '댓글올린날짜';
COMMENT ON COLUMN "REPLY"."REPLY_MODIFY_DATE" IS '댓글수정날짜';

-- insert query
-- INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, ?, ?, ?, DEFAULT, SYSDATE, SYSDATE)


-- 한 게시판에 해당하는 댓글 리스트 조회용 쿼리문
SELECT REPLY_NO, BOARD_NO, REPLY_CONTENT, USER_ID, R.REPLY_CREATE_DATE, R.REPLY_MODIFY_DATE, R.STATUS
FROM REPLY R
JOIN MEMBER M ON(R.REPLY_WRITER_NO = M.USER_NO)
WHERE R.STATUS='Y' AND BOARD_NO = 76
ORDER BY REPLY_CREATE_DATE DESC;


-- sys 에가서 비번 oracle 넣고 접속 후 다음을 입력하라
-- ALTER USER WEB ACCOUNT UNLOCK;


